git:
  depth: 1

language: java 

jdk:
- oraclejdk8

before_deploy:
  - "mvn package"
  - export FOO=$(ls target/foo-version-*.jar)

deploy:
  provider: releases
  api_key:
    secure: yep
  file: "${FOO}"
