git:
  depth: 1

language: java 

jdk:
- oraclejdk8

before_deploy:
  - "mvn package"
  - export FOO=$(ls target/logback-arangodb-*.jar)
  
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "$FOO"
  skip_cleanup: true
  on:
    tags: true

